version: "3.8"

services:
  clarinet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["clarinet", "check"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "test"]